export const COLOR_HANDKERCHIEF = {'Navy Dot' : 0, 'Navy Check': 1, 'Navy Glasses': 2,
                                     'Brown Gentleman': 3, 'Green Glasses': 4}

export const FONT_HANDKERCHIEF = {'White': 0, 'Black': 1, 'Navy': 2, 'Gray': 3, 'Skyblue': 4}


export const TYPE_HANDKERCHIEF = [
    ['HANDKERCHIEF_1','HANDKERCHIEF_2','HANDKERCHIEF_3','HANDKERCHIEF_4','HANDKERCHIEF_5'],
    ['HANDKERCHIEF_6','HANDKERCHIEF_7','HANDKERCHIEF_8','HANDKERCHIEF_9','HANDKERCHIEF_10'],
    ['HANDKERCHIEF_11','HANDKERCHIEF_12','HANDKERCHIEF_13','HANDKERCHIEF_14','HANDKERCHIEF_15'],
    ['HANDKERCHIEF_16','HANDKERCHIEF_17','HANDKERCHIEF_18','HANDKERCHIEF_19','HANDKERCHIEF_20'],
    ['HANDKERCHIEF_21','HANDKERCHIEF_22','HANDKERCHIEF_23','HANDKERCHIEF_24','HANDKERCHIEF_25']
  ];

  export const AGES = [
      20, 30, 40, 50, 60
  ]